name: Daily News Collection #260426

on:
  workflow_dispatch:        # 수동 실행 가능
  schedule:
    - cron: '50 22 * * *'  # 매일 KST 오전 7시 50분에 실행
    - cron: '10 5 * * *'  # 매일 KST 오후 2시 10분에 실행

jobs:
  collect-news:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
    - name: ✅ Checkout repository
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 📰 Run iRobotNews Collector
      run: python collect_irobotnews.py

    - name: 📰 Run AITimes Collector
      run: python collect_aitimes_news.py

    - name: 🧠 Run MIT News Collector
      run: python collect_MIT_news.py

    - name: 🧾 Run The Verge News Collector
      run: python collect_theverge_news.py

    - name: 💼 Run VentureBeat News Collector
      run: python collect_venturebeat_news.py

    - name:  Crunching Tech News
      run: python collect_techcrunch_news.py
 
